// Site data organized by category

// Enhanced site interface with search capabilities
export interface StreamingSite {
  name: string;
  description: string;
  features: string[];
  rating: number;
  status: string;
  lastUpdated: string;
  adLevel: string;
  url: string;
  searchUrl?: string; // Direct search URL pattern (use {query} as placeholder)
  hasSearch: boolean; // Whether the site has internal search
}

export const siteData = {
  "movies-shows": [
    {
      name: "1Shows",
      description: "Stream TV shows and movies with a clean interface and regular updates.",
      features: ["HD Quality", "No Registration", "Fast Loading"],
      rating: 4.7,
      status: "Working",
      lastUpdated: "2 days ago",
      adLevel: "Medium",
      url: "https://www.1shows.live/",
      searchUrl: "https://www.1shows.live/search?keyword={query}",
      hasSearch: true,
    },
    {
      name: "RgShows",
      description: "Watch the latest TV shows and movies with multiple streaming options.",
      features: ["Multiple Servers", "HD Streams", "User-friendly UI"],
      rating: 4.5,
      status: "Working",
      lastUpdated: "3 days ago",
      adLevel: "Medium",
      url: "https://www.rgshows.me/",
      searchUrl: "https://www.rgshows.me/search?q={query}",
      hasSearch: true,
    },
    {
      name: "FlickyStream",
      description: "Stream movies and TV shows with a modern interface and minimal ads.",
      features: ["Modern UI", "Fast Servers", "Low Ads"],
      rating: 4.8,
      status: "Working",
      lastUpdated: "1 day ago",
      adLevel: "Low",
      url: "https://flickystream.com/",
      searchUrl: "https://flickystream.com/search?q={query}",
      hasSearch: true,
    },
    {
      name: "P-Stream",
      description: "High-quality streaming platform for movies and TV series.",
      features: ["High Quality", "Fast Loading", "No Registration"],
      rating: 4.6,
      status: "Working",
      lastUpdated: "2 days ago",
      adLevel: "Medium",
      url: "https://pstream.org/",
      searchUrl: "https://pstream.org/search?q={query}",
      hasSearch: true,
    },
    {
      name: "CatFlix",
      description: "Netflix-style interface for streaming movies and TV shows.",
      features: ["Netflix-like UI", "HD Quality", "Recommendations"],
      rating: 4.9,
      status: "Working",
      lastUpdated: "1 day ago",
      adLevel: "Low",
      url: "https://catflix.su/home",
      searchUrl: "https://catflix.su/search/{query}",
      hasSearch: true,
    },
    {
      name: "CinemaDeck",
      description: "Stream the latest movies and TV shows with a clean, ad-light experience.",
      features: ["Latest Releases", "Clean UI", "Multiple Mirrors"],
      rating: 4.7,
      status: "Working",
      lastUpdated: "3 days ago",
      adLevel: "Low",
      url: "https://cinemadeck.com/",
      searchUrl: "https://cinemadeck.com/search?q={query}",
      hasSearch: true,
    },
    {
      name: "PopcornMovies",
      description: "User-friendly streaming site with a vast collection of movies and shows.",
      features: ["Large Library", "User Ratings", "Fast Servers"],
      rating: 4.5,
      status: "Working",
      lastUpdated: "4 days ago",
      adLevel: "Medium",
      url: "https://www.popcornmovies.to/home",
      searchUrl: "https://www.popcornmovies.to/search?keyword={query}",
      hasSearch: true,
    },
    {
      name: "Nepu",
      description: "Clean and simple interface for streaming movies and TV shows.",
      features: ["Simple UI", "Fast Loading", "HD Quality"],
      rating: 4.4,
      status: "Working",
      lastUpdated: "5 days ago",
      adLevel: "Medium",
      url: "https://nepu.to/",
      searchUrl: "https://nepu.to/search?q={query}",
      hasSearch: true,
    },
    {
      name: "BroFlix",
      description: "Stream movies and TV shows with multiple quality options.",
      features: ["Multiple Quality Options", "Fast Servers", "No Registration"],
      rating: 4.6,
      status: "Working",
      lastUpdated: "3 days ago",
      adLevel: "Medium",
      url: "https://broflix.cc/",
      searchUrl: "https://broflix.cc/search?keyword={query}",
      hasSearch: true,
    },
    {
      name: "Freek",
      description: "Free streaming platform with a wide selection of movies and shows.",
      features: ["Wide Selection", "Fast Updates", "User-friendly"],
      rating: 4.3,
      status: "Working",
      lastUpdated: "6 days ago",
      adLevel: "High",
      url: "https://freek.to/",
      searchUrl: "https://freek.to/search?q={query}",
      hasSearch: true,
    },
    {
      name: "Cineby",
      description: "International movie streaming site with a focus on diverse content.",
      features: ["International Content", "Multiple Languages", "Diverse Selection"],
      rating: 4.2,
      status: "Working",
      lastUpdated: "1 week ago",
      adLevel: "Medium",
      url: "https://www.cineby.ru/",
      searchUrl: "https://www.cineby.ru/search?q={query}",
      hasSearch: true,
    },
    {
      name: "RiveStream",
      description: "High-quality streaming for movies and TV shows with minimal interruptions.",
      features: ["High Quality", "Minimal Interruptions", "Fast Loading"],
      rating: 4.7,
      status: "Working",
      lastUpdated: "2 days ago",
      adLevel: "Low",
      url: "https://rivestream.org/",
      searchUrl: "https://rivestream.org/search?q={query}",
      hasSearch: true,
    },
    {
      name: "FMovies",
      description: "One of the most popular movie streaming sites with a vast library.",
      features: ["Huge Library", "Multiple Servers", "Regular Updates"],
      rating: 4.8,
      status: "Working",
      lastUpdated: "1 day ago",
      adLevel: "Medium",
      url: "https://fmovies-hd.to/home/",
      searchUrl: "https://fmovies-hd.to/search?keyword={query}",
      hasSearch: true,
    },
    {
      name: "Xprime",
      description: "Premium-feeling free streaming site for movies and TV shows.",
      features: ["Premium Feel", "HD Streams", "User Ratings"],
      rating: 4.6,
      status: "Working",
      lastUpdated: "3 days ago",
      adLevel: "Medium",
      url: "https://xprime.tv/",
      searchUrl: "https://xprime.tv/search?q={query}",
      hasSearch: true,
    },
    {
      name: "BFlix",
      description: "Clean interface with high-quality streams for movies and TV shows.",
      features: ["Clean UI", "HD Quality", "Fast Servers"],
      rating: 4.7,
      status: "Working",
      lastUpdated: "2 days ago",
      adLevel: "Low",
      url: "https://bflix.sh/home/",
      searchUrl: "https://bflix.sh/search?keyword={query}",
      hasSearch: true,
    },
    {
      name: "Hexa",
      description: "Modern streaming platform with a focus on user experience.",
      features: ["Modern UI", "User Experience", "Fast Loading"],
      rating: 4.5,
      status: "Working",
      lastUpdated: "4 days ago",
      adLevel: "Medium",
      url: "https://hexa.watch/",
      searchUrl: "https://hexa.watch/search?q={query}",
      hasSearch: true,
    },
    {
      name: "CorsFlux",
      description: "Stream movies and TV shows with multiple server options.",
      features: ["Multiple Servers", "HD Quality", "No Registration"],
      rating: 4.4,
      status: "Working",
      lastUpdated: "5 days ago",
      adLevel: "Medium",
      url: "https://corsflix.net/",
      searchUrl: "https://corsflix.net/search?q={query}",
      hasSearch: true,
    },
    {
      name: "Willow",
      description: "Simple and clean streaming site for movies and TV shows.",
      features: ["Simple UI", "Clean Design", "Fast Loading"],
      rating: 4.3,
      status: "Working",
      lastUpdated: "6 days ago",
      adLevel: "Medium",
      url: "https://willow.arlen.icu/",
      searchUrl: "https://willow.arlen.icu/search?q={query}",
      hasSearch: true,
    },
    {
      name: "StreamFlix",
      description: "Netflix-inspired streaming site with a wide selection of content.",
      features: ["Netflix-like UI", "Wide Selection", "HD Streams"],
      rating: 4.6,
      status: "Working",
      lastUpdated: "3 days ago",
      adLevel: "Medium",
      url: "https://watch.streamflix.one/",
      searchUrl: "https://watch.streamflix.one/search?q={query}",
      hasSearch: true,
    },
    {
      name: "456Movie",
      description: "User-friendly movie and TV streaming site with regular updates.",
      features: ["User-friendly", "Regular Updates", "Fast Servers"],
      rating: 4.5,
      status: "Working",
      lastUpdated: "4 days ago",
      adLevel: "Medium",
      url: "https://456movie.net/",
      searchUrl: "https://456movie.net/search?q={query}",
      hasSearch: true,
    },
  ],
  anime: [
    {
      name: "Miruro",
      description: "Clean and ad-free anime streaming site with a vast library.",
      features: ["Ad-Free", "Clean UI", "Large Library"],
      rating: 4.9,
      status: "Working",
      lastUpdated: "1 day ago",
      adLevel: "Low",
      url: "https://www.miruro.tv",
      searchUrl: "https://www.miruro.tv/search?q={query}",
      hasSearch: true,
    },
    {
      name: "HiAnime",
      description: "High-quality anime streaming with multiple video quality options.",
      features: ["HD Quality", "Multiple Quality Options", "Fast Updates"],
      rating: 4.8,
      status: "Working",
      lastUpdated: "2 days ago",
      adLevel: "Low",
      url: "https://hianime.to/home",
      searchUrl: "https://hianime.to/search?keyword={query}",
      hasSearch: true,
    },
    {
      name: "Enma",
      description: "Modern anime streaming site with a focus on seasonal anime.",
      features: ["Seasonal Anime", "Modern UI", "Fast Loading"],
      rating: 4.7,
      status: "Working",
      lastUpdated: "3 days ago",
      adLevel: "Low",
      url: "https://www.enma.lol",
      searchUrl: "https://www.enma.lol/search?q={query}",
      hasSearch: true,
    },
    {
      name: "AniWatch",
      description: "One of the most popular anime streaming sites with a vast library.",
      features: ["Huge Library", "User Ratings", "Multiple Servers"],
      rating: 4.9,
      status: "Working",
      lastUpdated: "1 day ago",
      adLevel: "Low",
      url: "https://aniwatchtv.to/home",
      searchUrl: "https://aniwatchtv.to/search?keyword={query}",
      hasSearch: true,
    },
    {
      name: "Animag",
      description: "User-friendly anime streaming site with regular updates.",
      features: ["User-friendly", "Regular Updates", "HD Quality"],
      rating: 4.6,
      status: "Working",
      lastUpdated: "4 days ago",
      adLevel: "Medium",
      url: "https://animag.to/",
      searchUrl: "https://animag.to/search?q={query}",
      hasSearch: true,
    },
    {
      name: "Kaido",
      description: "Clean interface anime streaming site with minimal ads.",
      features: ["Clean UI", "Minimal Ads", "Fast Loading"],
      rating: 4.7,
      status: "Working",
      lastUpdated: "3 days ago",
      adLevel: "Low",
      url: "https://kaido.to/home",
      searchUrl: "https://kaido.to/search?keyword={query}",
      hasSearch: true,
    },
    {
      name: "AniCrush",
      description: "Anime streaming site with a focus on user experience.",
      features: ["User Experience", "HD Streams", "Fast Updates"],
      rating: 4.6,
      status: "Working",
      lastUpdated: "4 days ago",
      adLevel: "Medium",
      url: "https://anicrush.to/home",
      searchUrl: "https://anicrush.to/search?q={query}",
      hasSearch: true,
    },
    {
      name: "RiveKun",
      description: "Part of RiveStream network, focused on anime content.",
      features: ["Part of RiveStream", "Fast Servers", "HD Quality"],
      rating: 4.7,
      status: "Working",
      lastUpdated: "3 days ago",
      adLevel: "Low",
      url: "https://rivekun.rivestream.org/",
      searchUrl: "https://rivekun.rivestream.org/search?q={query}",
      hasSearch: true,
    },
    {
      name: "KickAssAnime",
      description: "Long-running anime streaming site with a large community.",
      features: ["Large Community", "Wide Selection", "Multiple Servers"],
      rating: 4.5,
      status: "Working",
      lastUpdated: "5 days ago",
      adLevel: "Medium",
      url: "https://kickassanime.am/anime",
      searchUrl: "https://kickassanime.am/search?q={query}",
      hasSearch: true,
    },
    {
      name: "AnimeKai",
      description: "Modern anime streaming site with a clean interface.",
      features: ["Modern UI", "Clean Interface", "Fast Loading"],
      rating: 4.6,
      status: "Working",
      lastUpdated: "4 days ago",
      adLevel: "Medium",
      url: "https://animekai.to/home",
      searchUrl: "https://animekai.to/search?q={query}",
      hasSearch: true,
    },
    {
      name: "AnimeZ",
      description: "Anime streaming site with a focus on both new and classic anime.",
      features: ["New & Classic Anime", "User-friendly", "Fast Servers"],
      rating: 4.5,
      status: "Working",
      lastUpdated: "5 days ago",
      adLevel: "Medium",
      url: "https://animez.org/",
      searchUrl: "https://animez.org/search?q={query}",
      hasSearch: true,
    },
    {
      name: "Hikari",
      description: "Clean and simple anime streaming site with minimal ads.",
      features: ["Clean UI", "Minimal Ads", "Simple Navigation"],
      rating: 4.7,
      status: "Working",
      lastUpdated: "3 days ago",
      adLevel: "Low",
      url: "https://watch.hikaritv.xyz/",
      searchUrl: "https://watch.hikaritv.xyz/search?q={query}",
      hasSearch: true,
    },
  ],
  books: [
    {
      name: "MangaDex",
      description: "Community-driven manga reading platform with a vast library.",
      features: ["Community-driven", "Vast Library", "Multiple Languages"],
      rating: 4.9,
      status: "Working",
      lastUpdated: "1 day ago",
      adLevel: "Low",
      url: "https://mangadex.org/",
      searchUrl: "https://mangadex.org/search?q={query}",
      hasSearch: true,
    },
    {
      name: "Comick",
      description: "Fast and clean manga reading site with regular updates.",
      features: ["Fast Loading", "Clean UI", "Regular Updates"],
      rating: 4.8,
      status: "Working",
      lastUpdated: "2 days ago",
      adLevel: "Low",
      url: "https://comick.io/home2",
      searchUrl: "https://comick.io/search?q={query}",
      hasSearch: true,
    },
    {
      name: "MangaReader",
      description: "User-friendly manga reading site with a wide selection.",
      features: ["User-friendly", "Wide Selection", "Fast Loading"],
      rating: 4.7,
      status: "Working",
      lastUpdated: "3 days ago",
      adLevel: "Medium",
      url: "https://mangareader.to/home",
      searchUrl: "https://mangareader.to/search?keyword={query}",
      hasSearch: true,
    },
    {
      name: "Mangago",
      description: "Long-running manga site with a focus on various genres.",
      features: ["Various Genres", "Long-running", "Large Library"],
      rating: 4.6,
      status: "Working",
      lastUpdated: "4 days ago",
      adLevel: "Medium",
      url: "https://mangago.me/",
      searchUrl: "https://mangago.me/search/all?f=1&name={query}",
      hasSearch: true,
    },
    {
      name: "MangaFire",
      description: "Fast and responsive manga reading site with high-quality scans.",
      features: ["Fast & Responsive", "High-quality Scans", "User-friendly"],
      rating: 4.8,
      status: "Working",
      lastUpdated: "2 days ago",
      adLevel: "Medium",
      url: "https://mangafire.to/home",
      searchUrl: "https://mangafire.to/search?keyword={query}",
      hasSearch: true,
    },
    {
      name: "AllManga",
      description: "Comprehensive manga site with content from various countries.",
      features: ["Comprehensive", "International Content", "Regular Updates"],
      rating: 4.7,
      status: "Working",
      lastUpdated: "3 days ago",
      adLevel: "Medium",
      url: "https://allmanga.to/manga?cty=ALL",
      searchUrl: "https://allmanga.to/search?keyword={query}",
      hasSearch: true,
    },
    {
      name: "MangaKakalot",
      description: "Popular manga reading site with a vast collection.",
      features: ["Popular", "Vast Collection", "Fast Updates"],
      rating: 4.6,
      status: "Working",
      lastUpdated: "4 days ago",
      adLevel: "Medium",
      url: "https://mangakakalot.com/",
      searchUrl: "https://mangakakalot.com/search/story/{query}",
      hasSearch: true,
    },
    {
      name: "AsuraComic",
      description: "Focused on scanlation of manhwa and manga with fast releases.",
      features: ["Scanlation Focus", "Fast Releases", "High Quality"],
      rating: 4.7,
      status: "Working",
      lastUpdated: "3 days ago",
      adLevel: "Low",
      url: "https://asuracomic.net/",
      searchUrl: "https://asuracomic.net/?s={query}",
      hasSearch: true,
    },
    {
      name: "MangaHub",
      description: "User-friendly manga reading platform with a clean interface.",
      features: ["User-friendly", "Clean Interface", "Large Library"],
      rating: 4.5,
      status: "Working",
      lastUpdated: "5 days ago",
      adLevel: "Medium",
      url: "https://mangahub.io/",
      searchUrl: "https://mangahub.io/search?q={query}",
      hasSearch: true,
    },
    {
      name: "MangaPark",
      description: "Manga reading site with multiple reading options and layouts.",
      features: ["Multiple Reading Options", "Various Layouts", "Fast Loading"],
      rating: 4.6,
      status: "Working",
      lastUpdated: "4 days ago",
      adLevel: "Medium",
      url: "https://mangapark.io/",
      searchUrl: "https://mangapark.io/search?word={query}",
      hasSearch: true,
    },
    {
      name: "WeebCentral",
      description: "Manga and anime community site with a focus on discussion.",
      features: ["Community Focus", "Discussion", "Regular Updates"],
      rating: 4.4,
      status: "Working",
      lastUpdated: "6 days ago",
      adLevel: "Medium",
      url: "https://weebcentral.com/",
      searchUrl: "https://weebcentral.com/search?q={query}",
      hasSearch: true,
    },
    {
      name: "MangaKatana",
      description: "Fast and clean manga reading site with minimal ads.",
      features: ["Fast & Clean", "Minimal Ads", "User-friendly"],
      rating: 4.7,
      status: "Working",
      lastUpdated: "3 days ago",
      adLevel: "Low",
      url: "https://mangakatana.com/",
      searchUrl: "https://mangakatana.com/search?search={query}",
      hasSearch: true,
    },
  ],
  "live-tv": [
    {
      name: "TheTvApp",
      description: "Live TV streaming app with channels from around the world.",
      features: ["Global Channels", "Live Streaming", "User-friendly"],
      rating: 4.7,
      status: "Working",
      lastUpdated: "3 days ago",
      adLevel: "Medium",
      url: "https://thetvapp.to",
      hasSearch: false,
    },
    {
      name: "TV247",
      description: "24/7 live TV streaming with a wide range of channels.",
      features: ["24/7 Streaming", "Wide Range", "No Registration"],
      rating: 4.6,
      status: "Working",
      lastUpdated: "4 days ago",
      adLevel: "Medium",
      url: "https://tv247.us/all-channels/",
      hasSearch: false,
    },
    {
      name: "PublicIPTV",
      description: "Free IPTV service with channels from various countries.",
      features: ["Free IPTV", "International Channels", "Regular Updates"],
      rating: 4.5,
      status: "Working",
      lastUpdated: "5 days ago",
      adLevel: "Medium",
      url: "https://publiciptv.com/",
      hasSearch: false,
    },
    {
      name: "Sport+",
      description: "Sports-focused live TV streaming with coverage of major events.",
      features: ["Sports Focus", "Major Events", "HD Quality"],
      rating: 4.8,
      status: "Working",
      lastUpdated: "2 days ago",
      adLevel: "Medium",
      url: "https://en12.sportplus.live/",
      hasSearch: false,
    },
    {
      name: "StreamEast",
      description: "Sports streaming site with high-quality live broadcasts.",
      features: ["Sports Streaming", "High Quality", "Live Broadcasts"],
      rating: 4.7,
      status: "Working",
      lastUpdated: "3 days ago",
      adLevel: "Medium",
      url: "https://the.streameast.app/v86",
      hasSearch: false,
    },
    {
      name: "SportSurge",
      description: "Aggregator for sports streams with links to various events.",
      features: ["Sports Aggregator", "Various Events", "Multiple Sources"],
      rating: 4.6,
      status: "Working",
      lastUpdated: "4 days ago",
      adLevel: "Low",
      url: "https://v2.sportsurge.net/",
      hasSearch: false,
    },
    {
      name: "TV Garden",
      description: "Live TV streaming platform with a garden of channels.",
      features: ["Live TV", "Various Channels", "User-friendly"],
      rating: 4.5,
      status: "Working",
      lastUpdated: "5 days ago",
      adLevel: "Medium",
      url: "https://tv.garden/",
      hasSearch: false,
    },
    {
      name: "TOTV",
      description: "Live TV streaming with a focus on US channels.",
      features: ["US Channels", "Live Streaming", "Regular Updates"],
      rating: 4.4,
      status: "Working",
      lastUpdated: "6 days ago",
      adLevel: "Medium",
      url: "http://totv.org/tv/usa/",
      hasSearch: false,
    },
    {
      name: "RiveStream LiveSports",
      description: "Sports section of RiveStream with live sports coverage.",
      features: ["Live Sports", "Part of RiveStream", "HD Quality"],
      rating: 4.7,
      status: "Working",
      lastUpdated: "3 days ago",
      adLevel: "Low",
      url: "https://rivestream.org/livesports/",
      hasSearch: false,
    },
  ],
}

// Get all sites across all categories
export function getAllSites(): (StreamingSite & { category: string })[] {
  return [
    ...siteData["movies-shows"].map((site) => ({ ...site, category: "Movies & Shows" })),
    ...siteData.anime.map((site) => ({ ...site, category: "Anime" })),
    ...siteData.books.map((site) => ({ ...site, category: "Books" })),
    ...siteData["live-tv"].map((site) => ({ ...site, category: "Live TV" })),
  ]
}

// Get popular sites across all categories
export function getPopularSites(count = 6) {
  const allSites = getAllSites()

  // Sort by rating and return the top ones
  return allSites
    .sort((a, b) => b.rating - a.rating)
    .slice(0, count)
}

// Get sites by category
export function getSitesByCategory(category: string) {
  switch (category) {
    case "movies-shows":
      return siteData["movies-shows"]
    case "anime":
      return siteData.anime
    case "books":
      return siteData.books
    case "live-tv":
    case "sports":
      return siteData["live-tv"]
    default:
      return []
  }
}

// Search sites
export function searchSites(query: string) {
  if (!query) return []

  const allSites = getAllSites()

  // Case-insensitive search
  const lowerQuery = query.toLowerCase()

  return allSites.filter(
    (site) =>
      site.name.toLowerCase().includes(lowerQuery) ||
      site.description.toLowerCase().includes(lowerQuery) ||
      site.features.some((feature) => feature.toLowerCase().includes(lowerQuery)),
  )
}

// Generate direct search URL for a site and content title
export function generateDirectSearchUrl(site: StreamingSite, title: string): string {
  if (!site.searchUrl || !site.hasSearch) {
    return site.url
  }
  
  const encodedTitle = encodeURIComponent(title.toLowerCase())
  return site.searchUrl.replace('{query}', encodedTitle)
}
